### ISSUE TITLE
pour l'agenda de la page d'accueil

### ISSUE THREAD

**Issue by Fil** [QuartiersXXI/quartiersxxi#5]
on affiche dix événements, passés ou futurs ensemble (triés par date)

**Comment by rastapopougros** [comment]
Euh, on affiche des événements _passés_ sur l'accueil ? Je ne vois pas l'intérêt. :(

D'autant plus que s'ils entrent en base des événements pour dans longtemps, on verra en premier des choses hyper lointaines au lieu de voir le truc logique : les événements d'aujourd'hui et futurs qui arrivent, les plus proches en premiers (ce que fait très bien `{!evenement_passe}{par date_debut}`).
